apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: histocharts.dashboard.liqo.com
  annotations:
    description: 'This CRD is used to create generic histogram chart designs'
spec:
  group: dashboard.liqo.com
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: histocharts
    singular: histochart
    kind: HistoChart
    listKind: HistoChartList
    shortNames:
      - histos
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            values:
              description: Path to the values to use
              type: string
            labels:
              description: Path to the labels to use
              type: string
          required:
          - values
          - labels
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
