apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: views.dashboard.liqo.com
  annotations:
    description: 'This CRD is used to create custom views from a set of CRDs'
spec:
  group: dashboard.liqo.com
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: views
    singular: view
    kind: View
    listKind: ViewList
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              description: The name showed in the sidebar
              type: string
            layout:
              description: Layout that will be displayed
              type: object
            templates:
              description: Collection of CR template views
              items:
                properties:
                  name:
                    description: The name showed in the custom view for this CRD
                    type: string
                  kind:
                    description: The kind of a CRD we want to put in the view
                    type: string
                  template:
                    description: The path of a type template CRD custom resource (if default use the template in the CRD)
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
